apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  template:
    metadata:
      name: api-gateway
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: goceefake/api-gateway:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local-microservice
      restartPolicy: Always
  selector:
    matchLabels:
      app: api-gateway

---

apiVersion: v1
kind: Service
metadata:
  name: bankapp-api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 8080
      nodePort: 30020
  type: NodePort