server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: transaction-service
        uri: http://bankapp-transaction-service:8082/
        predicates:
        - Path=/transaction/**
      - id: account-service
        uri: http://bankapp-account-service:8081/
        predicates:
        - Path=/account/**
